### ISSUE TITLE
Verifying the peer's certificate

### ISSUE THREAD

**Issue by rslhdyt** [HarukaEduID/veritrans-php#2]
Error : 

> PHP message: PHP Notice:  Use of undefined constant CURL_SSLVERSION_TLSv1_0 - assumed 'CURL_SSLVERSION_TLSv1_0' in /home/deploy/htdocs/vt-endpoint/releases/20160510050854/vendor/veritrans/veritrans-php/Veritrans/ApiRequestor.php on line 83" while reading response header from upstream, client: 103.44.27.3, server: vt-endpoint.harukaedu.com, request: "POST /payment/notification HTTP/1.1", upstream: "fastcgi://127.0.0.1:5500", host: "vt-endpoint.harukaedu.com"

Environment :
- Produduction / Staging : centos 7 with php version 5.5.23

**Comment by williamn** [comment]
harukaeduid/veritrans-php#3 should fix this
